apiVersion: v1
kind: Namespace
metadata:
  name: lovable-clone

---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: lovable-clone
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP

