spring:
  application:
    name: lovable-clone
    description: working mock of lovable
  datasource:
    url: jdbc:postgresql://localhost:5432/lovable
    username: postgres
    password: '#Nishanth2026!'
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true





